NAME	:= liblist.a
SRCS	:= $(addsuffix .c, $(addprefix ft_list_, \
				init \
				reset \
				deinit \
				create_node \
				delete_node \
				push_front \
				push_back \
				push_at_index \
				pop_front \
				pop_back \
				pop_at_index \
				peek_front \
				peek_back \
				peek_at_index \
				map \
			))
LIBS	:= ../libstd/libstd.a

include ../misc/Makefile.lib.mk
