NAME	:= libstd.a
SRCS	:= $(addsuffix .c, $(addprefix ft_, \
				strlen \
				strndup \
				strdup \
				strcat \
				strcat_and_free \
				uitoa \
				itoa \
				strcmp \
				free \
			))
LIBS	:= ../liblist/liblist.a

include ../misc/Makefile.lib.mk
