NAME := libstd.a
SRCS := $(addsuffix .c, $(addprefix ft_, \
			bzero                        \
			free                         \
			memset                       \
			strlen                       \
		))

include ../misc/Makefile.lib.mk
