NAME := libtest.a
SRCS := $(addsuffix .c, $(addprefix ft_, \
			test_info                    \
			test_equal                   \
			test_nequal                  \
		))

include ../misc/Makefile.lib.mk
