NAME := libint.a
SRCS := $(addsuffix .c, $(addprefix ft_, \
			int_init                     \
			int_deinit                   \
			uint_init                    \
			uint_deinit                  \
		))
LIBS := ../libstd/libstd.a

include ../misc/Makefile.lib.mk
